FROM centos:7
MAINTAINER Tuhin Sharma <tusharma@redhat.com>

RUN yum install -y epel-release && \
    yum install -y zip && \
    yum install -y python-pip python-devel gcc && \
    yum -y install tkinter && \
    yum-config-manager --disable testing-devtools-2-centos-7 && \
    yum -y install gcc-c++.x86_64 && \
    yum clean all


# --------------------------------------------------------------------------------------------------
# install python packages
# --------------------------------------------------------------------------------------------------
COPY ./requirements.txt /
RUN pip install -r /requirements.txt && rm /requirements.txt




# --------------------------------------------------------------------------------------------------
# copy src code and scripts into root dir /
# the rest_api.py code assumes this dir structure
# --------------------------------------------------------------------------------------------------
COPY ./deployment/rest_api.py /rest_api.py
COPY ./src /src
COPY ./data /data


# --------------------------------------------------------------------------------------------------
# add entrypoint for the container
# --------------------------------------------------------------------------------------------------
ADD ./scripts/entrypoint.sh /bin/entrypoint.sh

ENTRYPOINT ["/bin/entrypoint.sh"]
